#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".
now="$(date +'%Y%m%d.%H%M%S')"
echo "S5LibLastCommit = $now" > S5LibLastCommit.lua
exec git add S5LibLastCommit.lua