---@diagnostic disable: duplicate-set-field

function CutsceneEditor.LoadUI()
	if not CppLogic.UI.TextButtonSetCenterText then
		function CppLogic.UI.TextButtonSetCenterText() end
	end
	assert(XGUIEng.GetWidgetID("CutsceneEditor")==0, "CutsceneEditor already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_Close")==0, "CutsceneEditor_Close already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_OpenUpdateRender")==0, "CutsceneEditor_OpenUpdateRender already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_Open")==0, "CutsceneEditor_Open already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_OpenText")==0, "CutsceneEditor_OpenText already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_OpenInput")==0, "CutsceneEditor_OpenInput already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_CSList")==0, "CutsceneEditor_CSList already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_CSListList")==0, "CutsceneEditor_CSListList already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_SelectCS")==0, "CutsceneEditor_SelectCS already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_CSListScroll")==0, "CutsceneEditor_CSListScroll already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_Edit")==0, "CutsceneEditor_Edit already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_Inv")==0, "CutsceneEditor_Inv already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_Flights")==0, "CutsceneEditor_Flights already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_FlightsTxt")==0, "CutsceneEditor_FlightsTxt already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_FlightList")==0, "CutsceneEditor_FlightList already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_SelectFlight")==0, "CutsceneEditor_SelectFlight already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_AddFlight")==0, "CutsceneEditor_AddFlight already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_RemoveFlight")==0, "CutsceneEditor_RemoveFlight already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_FlightUp")==0, "CutsceneEditor_FlightUp already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_FlightDown")==0, "CutsceneEditor_FlightDown already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_FlightScroll")==0, "CutsceneEditor_FlightScroll already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_Points")==0, "CutsceneEditor_Points already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_PointsTxt")==0, "CutsceneEditor_PointsTxt already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_PointsList")==0, "CutsceneEditor_PointsList already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_SelectPoint")==0, "CutsceneEditor_SelectPoint already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_AddPoint")==0, "CutsceneEditor_AddPoint already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_RemovePoint")==0, "CutsceneEditor_RemovePoint already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_PointUp")==0, "CutsceneEditor_PointUp already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_PointDown")==0, "CutsceneEditor_PointDown already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_PointScroll")==0, "CutsceneEditor_PointScroll already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_PointEdit")==0, "CutsceneEditor_PointEdit already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_CamLocTxt")==0, "CutsceneEditor_CamLocTxt already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_SetCamLoc")==0, "CutsceneEditor_SetCamLoc already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_ClearCamLoc")==0, "CutsceneEditor_ClearCamLoc already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_LookAtTxt")==0, "CutsceneEditor_LookAtTxt already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_SetLookAt")==0, "CutsceneEditor_SetLookAt already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_ClearLookAt")==0, "CutsceneEditor_ClearLookAt already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_FuncInput")==0, "CutsceneEditor_FuncInput already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_FuncTxt")==0, "CutsceneEditor_FuncTxt already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_JumpTo")==0, "CutsceneEditor_JumpTo already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_DurTxt")==0, "CutsceneEditor_DurTxt already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_Dur")==0, "CutsceneEditor_Dur already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_SpeedText")==0, "CutsceneEditor_SpeedText already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_Speed")==0, "CutsceneEditor_Speed already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_NumericCam")==0, "CutsceneEditor_NumericCam already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_NC_x")==0, "CutsceneEditor_NC_x already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_NC_y")==0, "CutsceneEditor_NC_y already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_NC_z")==0, "CutsceneEditor_NC_z already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_NC_xin")==0, "CutsceneEditor_NC_xin already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_NC_yin")==0, "CutsceneEditor_NC_yin already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_NC_zin")==0, "CutsceneEditor_NC_zin already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_NC_pitch")==0, "CutsceneEditor_NC_pitch already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_NC_yaw")==0, "CutsceneEditor_NC_yaw already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_NC_pitchin")==0, "CutsceneEditor_NC_pitchin already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_NC_yawin")==0, "CutsceneEditor_NC_yawin already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_NC_speed")==0, "CutsceneEditor_NC_speed already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_NC_speedin")==0, "CutsceneEditor_NC_speedin already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_ToSelect")==0, "CutsceneEditor_ToSelect already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_Export")==0, "CutsceneEditor_Export already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_PreviewFlight")==0, "CutsceneEditor_PreviewFlight already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_Preview")==0, "CutsceneEditor_Preview already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_ErrorMsg")==0, "CutsceneEditor_ErrorMsg already exists")
	assert(XGUIEng.GetWidgetID("CutsceneEditor_EditCamControl")==0, "CutsceneEditor_EditCamControl already exists")
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("Cinematic", "CutsceneEditor", "Cinematic_Text")
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor", 0, 0, 1024, 768)
	XGUIEng.ShowWidget("CutsceneEditor", 0)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("CutsceneEditor", "CutsceneEditor_Close", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_Close", 974, 748, 50, 20)
	XGUIEng.ShowWidget("CutsceneEditor_Close", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_Close", 0, false, false)
	XGUIEng.DisableButton("CutsceneEditor_Close", 0)
	XGUIEng.HighLightButton("CutsceneEditor_Close", 0)
	CppLogic.UI.ButtonOverrideActionFunc("CutsceneEditor_Close", function() CutsceneEditor.ExitEditor() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_Close", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_Close", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_Close", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_Close", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_Close", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_Close", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_Close", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_Close", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_Close", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_Close", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("CutsceneEditor_Close", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_Close", true)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_Close", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_Close", 0)
	XGUIEng.SetText("CutsceneEditor_Close", "@center close", 1)
	XGUIEng.SetTextColor("CutsceneEditor_Close", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("CutsceneEditor_Close", true)
	CppLogic.UI.ContainerWidgetCreateStaticTextWidgetChild("CutsceneEditor", "CutsceneEditor_OpenUpdateRender", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_OpenUpdateRender", 6, 627, 180, 25)
	XGUIEng.ShowWidget("CutsceneEditor_OpenUpdateRender", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_OpenUpdateRender", 0, false, false)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_OpenUpdateRender", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_OpenUpdateRender", 0, 100, 100, 100, 0)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_OpenUpdateRender", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_OpenUpdateRender", 0)
	XGUIEng.SetText("CutsceneEditor_OpenUpdateRender", "", 1)
	XGUIEng.SetTextColor("CutsceneEditor_OpenUpdateRender", 255, 255, 255, 255)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_OpenUpdateRender", false)
	CppLogic.UI.WidgetOverrideUpdateFunc("CutsceneEditor_OpenUpdateRender", function() CutsceneEditor.JumpHeightOverTerrain() end)
	XGUIEng.SetLinesToPrint("CutsceneEditor_OpenUpdateRender", 0, 0)
	CppLogic.UI.StaticTextWidgetSetLineDistanceFactor("CutsceneEditor_OpenUpdateRender", 0)
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("CutsceneEditor", "CutsceneEditor_Open", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_Open", 0, 0, 1024, 768)
	XGUIEng.ShowWidget("CutsceneEditor_Open", 0)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_Open", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateStaticTextWidgetChild("CutsceneEditor_Open", "CutsceneEditor_OpenText", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_OpenText", 5, 615, 200, 20)
	XGUIEng.ShowWidget("CutsceneEditor_OpenText", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_OpenText", 0, false, false)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_OpenText", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_OpenText", 0, 100, 100, 100, 0)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_OpenText", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_OpenText", 0)
	XGUIEng.SetText("CutsceneEditor_OpenText", "open/create cutscene:", 1)
	XGUIEng.SetTextColor("CutsceneEditor_OpenText", 255, 255, 255, 255)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_OpenText", true)
	XGUIEng.SetLinesToPrint("CutsceneEditor_OpenText", 0, 0)
	CppLogic.UI.StaticTextWidgetSetLineDistanceFactor("CutsceneEditor_OpenText", 0)
	CppLogic.UI.ContainerWidgetCreateCustomWidgetChild("CutsceneEditor_Open", "CutsceneEditor_OpenInput", "CppLogic::Mod::UI::TextInputCustomWidget", nil, 0, 0, 0, 0, -2090572700, 0, "CutsceneEditor.Open", "menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_OpenInput", 250, 615, 700, 20)
	XGUIEng.ShowWidget("CutsceneEditor_OpenInput", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_OpenInput", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("CutsceneEditor_Open", "CutsceneEditor_CSList", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_CSList", 0, 618, 200, 150)
	XGUIEng.ShowWidget("CutsceneEditor_CSList", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_CSList", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("CutsceneEditor_CSList", "CutsceneEditor_CSListList", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_CSListList", 0, 25, 200, 125)
	XGUIEng.ShowWidget("CutsceneEditor_CSListList", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_CSListList", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("CutsceneEditor_CSListList", "CutsceneEditor_SelectCS", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_SelectCS", 0, 0, 200, 20)
	XGUIEng.ShowWidget("CutsceneEditor_SelectCS", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_SelectCS", 0, false, false)
	XGUIEng.DisableButton("CutsceneEditor_SelectCS", 0)
	XGUIEng.HighLightButton("CutsceneEditor_SelectCS", 0)
	CppLogic.UI.ButtonOverrideActionFunc("CutsceneEditor_SelectCS", function() CutsceneEditor.ActionCutsceneName() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SelectCS", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SelectCS", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SelectCS", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SelectCS", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SelectCS", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SelectCS", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SelectCS", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SelectCS", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SelectCS", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SelectCS", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("CutsceneEditor_SelectCS", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_SelectCS", false)
	CppLogic.UI.WidgetOverrideUpdateFunc("CutsceneEditor_SelectCS", function() CutsceneEditor.UpdateCutsceneName() end)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_SelectCS", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_SelectCS", 0)
	XGUIEng.SetText("CutsceneEditor_SelectCS", "@center name", 1)
	XGUIEng.SetTextColor("CutsceneEditor_SelectCS", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("CutsceneEditor_SelectCS", true)
	CppLogic.UI.ContainerWidgetCreateCustomWidgetChild("CutsceneEditor_CSList", "CutsceneEditor_CSListScroll", "CppLogic::Mod::UI::AutoScrollCustomWidget", nil, 1, 0, 0, 0, 0, 0, "", "CutsceneEditor_SelectCS")
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_CSListScroll", 0, 25, 200, 125)
	XGUIEng.ShowWidget("CutsceneEditor_CSListScroll", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_CSListScroll", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("CutsceneEditor", "CutsceneEditor_Edit", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_Edit", 0, 0, 1024, 768)
	XGUIEng.ShowWidget("CutsceneEditor_Edit", 0)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_Edit", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("CutsceneEditor_Edit", "CutsceneEditor_Inv", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_Inv", 380, 10, 40, 20)
	XGUIEng.ShowWidget("CutsceneEditor_Inv", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_Inv", 0, false, false)
	XGUIEng.DisableButton("CutsceneEditor_Inv", 0)
	XGUIEng.HighLightButton("CutsceneEditor_Inv", 0)
	CppLogic.UI.ButtonOverrideActionFunc("CutsceneEditor_Inv", function() CutsceneEditor.ActionToggleInv() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_Inv", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_Inv", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_Inv", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_Inv", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_Inv", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_Inv", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_Inv", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_Inv", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_Inv", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_Inv", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("CutsceneEditor_Inv", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_Inv", false)
	CppLogic.UI.WidgetOverrideUpdateFunc("CutsceneEditor_Inv", function() CutsceneEditor.UpdateToggleInv() end)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_Inv", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_Inv", 0)
	XGUIEng.SetText("CutsceneEditor_Inv", "@center inv", 1)
	XGUIEng.SetTextColor("CutsceneEditor_Inv", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("CutsceneEditor_Inv", true)
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("CutsceneEditor_Edit", "CutsceneEditor_Flights", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_Flights", 0, 618, 200, 150)
	XGUIEng.ShowWidget("CutsceneEditor_Flights", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_Flights", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateStaticTextWidgetChild("CutsceneEditor_Flights", "CutsceneEditor_FlightsTxt", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_FlightsTxt", 5, 0, 50, 20)
	XGUIEng.ShowWidget("CutsceneEditor_FlightsTxt", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_FlightsTxt", 0, false, false)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_FlightsTxt", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_FlightsTxt", 0, 100, 100, 100, 0)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_FlightsTxt", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_FlightsTxt", 0)
	XGUIEng.SetText("CutsceneEditor_FlightsTxt", "flights:", 1)
	XGUIEng.SetTextColor("CutsceneEditor_FlightsTxt", 255, 255, 255, 255)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_FlightsTxt", true)
	XGUIEng.SetLinesToPrint("CutsceneEditor_FlightsTxt", 0, 0)
	CppLogic.UI.StaticTextWidgetSetLineDistanceFactor("CutsceneEditor_FlightsTxt", 0)
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("CutsceneEditor_Flights", "CutsceneEditor_FlightList", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_FlightList", 0, 25, 200, 125)
	XGUIEng.ShowWidget("CutsceneEditor_FlightList", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_FlightList", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("CutsceneEditor_FlightList", "CutsceneEditor_SelectFlight", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_SelectFlight", 0, 0, 200, 20)
	XGUIEng.ShowWidget("CutsceneEditor_SelectFlight", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_SelectFlight", 0, false, false)
	XGUIEng.DisableButton("CutsceneEditor_SelectFlight", 0)
	XGUIEng.HighLightButton("CutsceneEditor_SelectFlight", 0)
	CppLogic.UI.ButtonOverrideActionFunc("CutsceneEditor_SelectFlight", function() CutsceneEditor.ActionFlight() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SelectFlight", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SelectFlight", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SelectFlight", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SelectFlight", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SelectFlight", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SelectFlight", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SelectFlight", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SelectFlight", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SelectFlight", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SelectFlight", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("CutsceneEditor_SelectFlight", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_SelectFlight", false)
	CppLogic.UI.WidgetOverrideUpdateFunc("CutsceneEditor_SelectFlight", function() CutsceneEditor.UpdateFlight() end)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_SelectFlight", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_SelectFlight", 0)
	XGUIEng.SetText("CutsceneEditor_SelectFlight", "@center name", 1)
	XGUIEng.SetTextColor("CutsceneEditor_SelectFlight", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("CutsceneEditor_SelectFlight", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("CutsceneEditor_Flights", "CutsceneEditor_AddFlight", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_AddFlight", 60, 0, 30, 20)
	XGUIEng.ShowWidget("CutsceneEditor_AddFlight", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_AddFlight", 0, false, false)
	XGUIEng.DisableButton("CutsceneEditor_AddFlight", 0)
	XGUIEng.HighLightButton("CutsceneEditor_AddFlight", 0)
	CppLogic.UI.ButtonOverrideActionFunc("CutsceneEditor_AddFlight", function() CutsceneEditor.AddFlight() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_AddFlight", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_AddFlight", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_AddFlight", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_AddFlight", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_AddFlight", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_AddFlight", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_AddFlight", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_AddFlight", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_AddFlight", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_AddFlight", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("CutsceneEditor_AddFlight", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_AddFlight", true)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_AddFlight", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_AddFlight", 0)
	XGUIEng.SetText("CutsceneEditor_AddFlight", "@center add", 1)
	XGUIEng.SetTextColor("CutsceneEditor_AddFlight", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("CutsceneEditor_AddFlight", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("CutsceneEditor_Flights", "CutsceneEditor_RemoveFlight", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_RemoveFlight", 95, 0, 55, 20)
	XGUIEng.ShowWidget("CutsceneEditor_RemoveFlight", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_RemoveFlight", 0, false, false)
	XGUIEng.DisableButton("CutsceneEditor_RemoveFlight", 0)
	XGUIEng.HighLightButton("CutsceneEditor_RemoveFlight", 0)
	CppLogic.UI.ButtonOverrideActionFunc("CutsceneEditor_RemoveFlight", function() CutsceneEditor.RemoveFlight() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_RemoveFlight", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_RemoveFlight", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_RemoveFlight", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_RemoveFlight", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_RemoveFlight", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_RemoveFlight", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_RemoveFlight", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_RemoveFlight", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_RemoveFlight", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_RemoveFlight", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("CutsceneEditor_RemoveFlight", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_RemoveFlight", true)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_RemoveFlight", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_RemoveFlight", 0)
	XGUIEng.SetText("CutsceneEditor_RemoveFlight", "remove", 1)
	XGUIEng.SetTextColor("CutsceneEditor_RemoveFlight", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("CutsceneEditor_RemoveFlight", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("CutsceneEditor_Flights", "CutsceneEditor_FlightUp", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_FlightUp", 155, 0, 20, 20)
	XGUIEng.ShowWidget("CutsceneEditor_FlightUp", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_FlightUp", 0, false, false)
	XGUIEng.DisableButton("CutsceneEditor_FlightUp", 0)
	XGUIEng.HighLightButton("CutsceneEditor_FlightUp", 0)
	CppLogic.UI.ButtonOverrideActionFunc("CutsceneEditor_FlightUp", function() CutsceneEditor.FlightUp() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_FlightUp", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_FlightUp", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_FlightUp", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_FlightUp", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_FlightUp", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_FlightUp", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_FlightUp", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_FlightUp", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_FlightUp", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_FlightUp", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("CutsceneEditor_FlightUp", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_FlightUp", true)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_FlightUp", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_FlightUp", 0)
	XGUIEng.SetText("CutsceneEditor_FlightUp", "@center up", 1)
	XGUIEng.SetTextColor("CutsceneEditor_FlightUp", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("CutsceneEditor_FlightUp", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("CutsceneEditor_Flights", "CutsceneEditor_FlightDown", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_FlightDown", 180, 0, 20, 20)
	XGUIEng.ShowWidget("CutsceneEditor_FlightDown", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_FlightDown", 0, false, false)
	XGUIEng.DisableButton("CutsceneEditor_FlightDown", 0)
	XGUIEng.HighLightButton("CutsceneEditor_FlightDown", 0)
	CppLogic.UI.ButtonOverrideActionFunc("CutsceneEditor_FlightDown", function() CutsceneEditor.FlightDown() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_FlightDown", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_FlightDown", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_FlightDown", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_FlightDown", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_FlightDown", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_FlightDown", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_FlightDown", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_FlightDown", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_FlightDown", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_FlightDown", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("CutsceneEditor_FlightDown", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_FlightDown", true)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_FlightDown", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_FlightDown", 0)
	XGUIEng.SetText("CutsceneEditor_FlightDown", "@center v", 1)
	XGUIEng.SetTextColor("CutsceneEditor_FlightDown", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("CutsceneEditor_FlightDown", true)
	CppLogic.UI.ContainerWidgetCreateCustomWidgetChild("CutsceneEditor_Flights", "CutsceneEditor_FlightScroll", "CppLogic::Mod::UI::AutoScrollCustomWidget", nil, 1, 0, 0, 0, 0, 0, "", "CutsceneEditor_SelectFlight")
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_FlightScroll", 0, 25, 200, 125)
	XGUIEng.ShowWidget("CutsceneEditor_FlightScroll", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_FlightScroll", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("CutsceneEditor_Edit", "CutsceneEditor_Points", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_Points", 205, 618, 200, 150)
	XGUIEng.ShowWidget("CutsceneEditor_Points", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_Points", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateStaticTextWidgetChild("CutsceneEditor_Points", "CutsceneEditor_PointsTxt", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_PointsTxt", 5, 0, 50, 20)
	XGUIEng.ShowWidget("CutsceneEditor_PointsTxt", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_PointsTxt", 0, false, false)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_PointsTxt", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_PointsTxt", 0, 100, 100, 100, 0)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_PointsTxt", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_PointsTxt", 0)
	XGUIEng.SetText("CutsceneEditor_PointsTxt", "points:", 1)
	XGUIEng.SetTextColor("CutsceneEditor_PointsTxt", 255, 255, 255, 255)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_PointsTxt", true)
	XGUIEng.SetLinesToPrint("CutsceneEditor_PointsTxt", 0, 0)
	CppLogic.UI.StaticTextWidgetSetLineDistanceFactor("CutsceneEditor_PointsTxt", 0)
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("CutsceneEditor_Points", "CutsceneEditor_PointsList", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_PointsList", 0, 25, 200, 125)
	XGUIEng.ShowWidget("CutsceneEditor_PointsList", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_PointsList", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("CutsceneEditor_PointsList", "CutsceneEditor_SelectPoint", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_SelectPoint", 0, 0, 200, 20)
	XGUIEng.ShowWidget("CutsceneEditor_SelectPoint", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_SelectPoint", 0, false, false)
	XGUIEng.DisableButton("CutsceneEditor_SelectPoint", 0)
	XGUIEng.HighLightButton("CutsceneEditor_SelectPoint", 0)
	CppLogic.UI.ButtonOverrideActionFunc("CutsceneEditor_SelectPoint", function() CutsceneEditor.ActionPoint() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SelectPoint", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SelectPoint", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SelectPoint", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SelectPoint", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SelectPoint", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SelectPoint", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SelectPoint", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SelectPoint", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SelectPoint", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SelectPoint", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("CutsceneEditor_SelectPoint", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_SelectPoint", false)
	CppLogic.UI.WidgetOverrideUpdateFunc("CutsceneEditor_SelectPoint", function() CutsceneEditor.UpdatePoint() end)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_SelectPoint", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_SelectPoint", 0)
	XGUIEng.SetText("CutsceneEditor_SelectPoint", "@center name", 1)
	XGUIEng.SetTextColor("CutsceneEditor_SelectPoint", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("CutsceneEditor_SelectPoint", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("CutsceneEditor_Points", "CutsceneEditor_AddPoint", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_AddPoint", 60, 0, 30, 20)
	XGUIEng.ShowWidget("CutsceneEditor_AddPoint", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_AddPoint", 0, false, false)
	XGUIEng.DisableButton("CutsceneEditor_AddPoint", 0)
	XGUIEng.HighLightButton("CutsceneEditor_AddPoint", 0)
	CppLogic.UI.ButtonOverrideActionFunc("CutsceneEditor_AddPoint", function() CutsceneEditor.AddPoint() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_AddPoint", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_AddPoint", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_AddPoint", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_AddPoint", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_AddPoint", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_AddPoint", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_AddPoint", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_AddPoint", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_AddPoint", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_AddPoint", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("CutsceneEditor_AddPoint", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_AddPoint", true)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_AddPoint", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_AddPoint", 0)
	XGUIEng.SetText("CutsceneEditor_AddPoint", "@center add", 1)
	XGUIEng.SetTextColor("CutsceneEditor_AddPoint", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("CutsceneEditor_AddPoint", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("CutsceneEditor_Points", "CutsceneEditor_RemovePoint", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_RemovePoint", 95, 0, 55, 20)
	XGUIEng.ShowWidget("CutsceneEditor_RemovePoint", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_RemovePoint", 0, false, false)
	XGUIEng.DisableButton("CutsceneEditor_RemovePoint", 0)
	XGUIEng.HighLightButton("CutsceneEditor_RemovePoint", 0)
	CppLogic.UI.ButtonOverrideActionFunc("CutsceneEditor_RemovePoint", function() CutsceneEditor.RemovePoint() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_RemovePoint", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_RemovePoint", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_RemovePoint", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_RemovePoint", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_RemovePoint", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_RemovePoint", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_RemovePoint", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_RemovePoint", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_RemovePoint", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_RemovePoint", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("CutsceneEditor_RemovePoint", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_RemovePoint", true)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_RemovePoint", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_RemovePoint", 0)
	XGUIEng.SetText("CutsceneEditor_RemovePoint", "@center remove", 1)
	XGUIEng.SetTextColor("CutsceneEditor_RemovePoint", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("CutsceneEditor_RemovePoint", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("CutsceneEditor_Points", "CutsceneEditor_PointUp", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_PointUp", 155, 0, 20, 20)
	XGUIEng.ShowWidget("CutsceneEditor_PointUp", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_PointUp", 0, false, false)
	XGUIEng.DisableButton("CutsceneEditor_PointUp", 0)
	XGUIEng.HighLightButton("CutsceneEditor_PointUp", 0)
	CppLogic.UI.ButtonOverrideActionFunc("CutsceneEditor_PointUp", function() CutsceneEditor.PointUp() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_PointUp", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_PointUp", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_PointUp", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_PointUp", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_PointUp", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_PointUp", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_PointUp", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_PointUp", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_PointUp", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_PointUp", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("CutsceneEditor_PointUp", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_PointUp", true)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_PointUp", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_PointUp", 0)
	XGUIEng.SetText("CutsceneEditor_PointUp", "@center up", 1)
	XGUIEng.SetTextColor("CutsceneEditor_PointUp", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("CutsceneEditor_PointUp", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("CutsceneEditor_Points", "CutsceneEditor_PointDown", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_PointDown", 180, 0, 20, 20)
	XGUIEng.ShowWidget("CutsceneEditor_PointDown", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_PointDown", 0, false, false)
	XGUIEng.DisableButton("CutsceneEditor_PointDown", 0)
	XGUIEng.HighLightButton("CutsceneEditor_PointDown", 0)
	CppLogic.UI.ButtonOverrideActionFunc("CutsceneEditor_PointDown", function() CutsceneEditor.PointDown() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_PointDown", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_PointDown", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_PointDown", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_PointDown", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_PointDown", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_PointDown", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_PointDown", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_PointDown", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_PointDown", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_PointDown", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("CutsceneEditor_PointDown", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_PointDown", true)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_PointDown", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_PointDown", 0)
	XGUIEng.SetText("CutsceneEditor_PointDown", "@center v", 1)
	XGUIEng.SetTextColor("CutsceneEditor_PointDown", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("CutsceneEditor_PointDown", true)
	CppLogic.UI.ContainerWidgetCreateCustomWidgetChild("CutsceneEditor_Points", "CutsceneEditor_PointScroll", "CppLogic::Mod::UI::AutoScrollCustomWidget", nil, 1, 0, 0, 0, 0, 0, "", "CutsceneEditor_SelectPoint")
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_PointScroll", 0, 25, 200, 125)
	XGUIEng.ShowWidget("CutsceneEditor_PointScroll", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_PointScroll", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("CutsceneEditor_Edit", "CutsceneEditor_PointEdit", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_PointEdit", 410, 618, 525, 150)
	XGUIEng.ShowWidget("CutsceneEditor_PointEdit", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_PointEdit", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateStaticTextWidgetChild("CutsceneEditor_PointEdit", "CutsceneEditor_CamLocTxt", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_CamLocTxt", 5, 5, 120, 20)
	XGUIEng.ShowWidget("CutsceneEditor_CamLocTxt", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_CamLocTxt", 0, false, false)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_CamLocTxt", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_CamLocTxt", 0, 100, 100, 100, 0)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_CamLocTxt", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_CamLocTxt", 0)
	XGUIEng.SetText("CutsceneEditor_CamLocTxt", "camera location", 1)
	XGUIEng.SetTextColor("CutsceneEditor_CamLocTxt", 255, 255, 255, 255)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_CamLocTxt", true)
	XGUIEng.SetLinesToPrint("CutsceneEditor_CamLocTxt", 0, 0)
	CppLogic.UI.StaticTextWidgetSetLineDistanceFactor("CutsceneEditor_CamLocTxt", 0)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("CutsceneEditor_PointEdit", "CutsceneEditor_SetCamLoc", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_SetCamLoc", 125, 5, 35, 20)
	XGUIEng.ShowWidget("CutsceneEditor_SetCamLoc", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_SetCamLoc", 0, false, false)
	XGUIEng.DisableButton("CutsceneEditor_SetCamLoc", 0)
	XGUIEng.HighLightButton("CutsceneEditor_SetCamLoc", 0)
	CppLogic.UI.ButtonOverrideActionFunc("CutsceneEditor_SetCamLoc", function() CutsceneEditor.SetCamPos() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SetCamLoc", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SetCamLoc", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SetCamLoc", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SetCamLoc", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SetCamLoc", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SetCamLoc", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SetCamLoc", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SetCamLoc", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SetCamLoc", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SetCamLoc", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("CutsceneEditor_SetCamLoc", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_SetCamLoc", true)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_SetCamLoc", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_SetCamLoc", 0)
	XGUIEng.SetText("CutsceneEditor_SetCamLoc", "@center set", 1)
	XGUIEng.SetTextColor("CutsceneEditor_SetCamLoc", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("CutsceneEditor_SetCamLoc", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("CutsceneEditor_PointEdit", "CutsceneEditor_ClearCamLoc", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_ClearCamLoc", 165, 5, 35, 20)
	XGUIEng.ShowWidget("CutsceneEditor_ClearCamLoc", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_ClearCamLoc", 0, false, false)
	XGUIEng.DisableButton("CutsceneEditor_ClearCamLoc", 0)
	XGUIEng.HighLightButton("CutsceneEditor_ClearCamLoc", 0)
	CppLogic.UI.ButtonOverrideActionFunc("CutsceneEditor_ClearCamLoc", function() CutsceneEditor.ClearCamPos() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_ClearCamLoc", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_ClearCamLoc", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_ClearCamLoc", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_ClearCamLoc", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_ClearCamLoc", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_ClearCamLoc", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_ClearCamLoc", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_ClearCamLoc", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_ClearCamLoc", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_ClearCamLoc", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("CutsceneEditor_ClearCamLoc", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_ClearCamLoc", true)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_ClearCamLoc", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_ClearCamLoc", 0)
	XGUIEng.SetText("CutsceneEditor_ClearCamLoc", "@center clear", 1)
	XGUIEng.SetTextColor("CutsceneEditor_ClearCamLoc", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("CutsceneEditor_ClearCamLoc", true)
	CppLogic.UI.ContainerWidgetCreateStaticTextWidgetChild("CutsceneEditor_PointEdit", "CutsceneEditor_LookAtTxt", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_LookAtTxt", 5, 30, 120, 20)
	XGUIEng.ShowWidget("CutsceneEditor_LookAtTxt", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_LookAtTxt", 0, false, false)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_LookAtTxt", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_LookAtTxt", 0, 100, 100, 100, 0)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_LookAtTxt", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_LookAtTxt", 0)
	XGUIEng.SetText("CutsceneEditor_LookAtTxt", "look at", 1)
	XGUIEng.SetTextColor("CutsceneEditor_LookAtTxt", 255, 255, 255, 255)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_LookAtTxt", true)
	XGUIEng.SetLinesToPrint("CutsceneEditor_LookAtTxt", 0, 0)
	CppLogic.UI.StaticTextWidgetSetLineDistanceFactor("CutsceneEditor_LookAtTxt", 0)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("CutsceneEditor_PointEdit", "CutsceneEditor_SetLookAt", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_SetLookAt", 125, 30, 35, 20)
	XGUIEng.ShowWidget("CutsceneEditor_SetLookAt", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_SetLookAt", 0, false, false)
	XGUIEng.DisableButton("CutsceneEditor_SetLookAt", 0)
	XGUIEng.HighLightButton("CutsceneEditor_SetLookAt", 0)
	CppLogic.UI.ButtonOverrideActionFunc("CutsceneEditor_SetLookAt", function() CutsceneEditor.SetLookAt() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SetLookAt", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SetLookAt", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SetLookAt", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SetLookAt", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SetLookAt", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SetLookAt", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SetLookAt", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SetLookAt", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SetLookAt", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SetLookAt", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("CutsceneEditor_SetLookAt", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_SetLookAt", true)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_SetLookAt", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_SetLookAt", 0)
	XGUIEng.SetText("CutsceneEditor_SetLookAt", "@center set", 1)
	XGUIEng.SetTextColor("CutsceneEditor_SetLookAt", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("CutsceneEditor_SetLookAt", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("CutsceneEditor_PointEdit", "CutsceneEditor_ClearLookAt", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_ClearLookAt", 165, 30, 35, 20)
	XGUIEng.ShowWidget("CutsceneEditor_ClearLookAt", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_ClearLookAt", 0, false, false)
	XGUIEng.DisableButton("CutsceneEditor_ClearLookAt", 0)
	XGUIEng.HighLightButton("CutsceneEditor_ClearLookAt", 0)
	CppLogic.UI.ButtonOverrideActionFunc("CutsceneEditor_ClearLookAt", function() CutsceneEditor.ClearLookAt() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_ClearLookAt", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_ClearLookAt", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_ClearLookAt", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_ClearLookAt", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_ClearLookAt", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_ClearLookAt", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_ClearLookAt", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_ClearLookAt", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_ClearLookAt", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_ClearLookAt", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("CutsceneEditor_ClearLookAt", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_ClearLookAt", true)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_ClearLookAt", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_ClearLookAt", 0)
	XGUIEng.SetText("CutsceneEditor_ClearLookAt", "@center clear", 1)
	XGUIEng.SetTextColor("CutsceneEditor_ClearLookAt", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("CutsceneEditor_ClearLookAt", true)
	CppLogic.UI.ContainerWidgetCreateCustomWidgetChild("CutsceneEditor_PointEdit", "CutsceneEditor_FuncInput", "CppLogic::Mod::UI::TextInputCustomWidget", nil, 0, 0, 0, 0, -2090572700, 0, "CutsceneEditor.SetFunc", "menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_FuncInput", 125, 55, 400, 20)
	XGUIEng.ShowWidget("CutsceneEditor_FuncInput", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_FuncInput", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateStaticTextWidgetChild("CutsceneEditor_PointEdit", "CutsceneEditor_FuncTxt", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_FuncTxt", 5, 55, 90, 20)
	XGUIEng.ShowWidget("CutsceneEditor_FuncTxt", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_FuncTxt", 0, false, false)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_FuncTxt", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_FuncTxt", 0, 100, 100, 100, 0)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_FuncTxt", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_FuncTxt", 0)
	XGUIEng.SetText("CutsceneEditor_FuncTxt", "func", 1)
	XGUIEng.SetTextColor("CutsceneEditor_FuncTxt", 255, 255, 255, 255)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_FuncTxt", true)
	XGUIEng.SetLinesToPrint("CutsceneEditor_FuncTxt", 0, 0)
	CppLogic.UI.StaticTextWidgetSetLineDistanceFactor("CutsceneEditor_FuncTxt", 0)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("CutsceneEditor_PointEdit", "CutsceneEditor_JumpTo", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_JumpTo", 125, 130, 70, 20)
	XGUIEng.ShowWidget("CutsceneEditor_JumpTo", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_JumpTo", 0, false, false)
	XGUIEng.DisableButton("CutsceneEditor_JumpTo", 0)
	XGUIEng.HighLightButton("CutsceneEditor_JumpTo", 0)
	CppLogic.UI.ButtonOverrideActionFunc("CutsceneEditor_JumpTo", function() CutsceneEditor.JumpToElement() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_JumpTo", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_JumpTo", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_JumpTo", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_JumpTo", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_JumpTo", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_JumpTo", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_JumpTo", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_JumpTo", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_JumpTo", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_JumpTo", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("CutsceneEditor_JumpTo", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_JumpTo", true)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_JumpTo", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_JumpTo", 0)
	XGUIEng.SetText("CutsceneEditor_JumpTo", "@center jump to", 1)
	XGUIEng.SetTextColor("CutsceneEditor_JumpTo", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("CutsceneEditor_JumpTo", true)
	CppLogic.UI.ContainerWidgetCreateStaticTextWidgetChild("CutsceneEditor_PointEdit", "CutsceneEditor_DurTxt", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_DurTxt", 225, 5, 90, 20)
	XGUIEng.ShowWidget("CutsceneEditor_DurTxt", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_DurTxt", 0, false, false)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_DurTxt", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_DurTxt", 0, 100, 100, 100, 0)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_DurTxt", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_DurTxt", 0)
	XGUIEng.SetText("CutsceneEditor_DurTxt", "duration:", 1)
	XGUIEng.SetTextColor("CutsceneEditor_DurTxt", 255, 255, 255, 255)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_DurTxt", true)
	XGUIEng.SetLinesToPrint("CutsceneEditor_DurTxt", 0, 0)
	CppLogic.UI.StaticTextWidgetSetLineDistanceFactor("CutsceneEditor_DurTxt", 0)
	CppLogic.UI.ContainerWidgetCreateCustomWidgetChild("CutsceneEditor_PointEdit", "CutsceneEditor_Dur", "CppLogic::Mod::UI::TextInputCustomWidget", nil, 5, 0, 0, 0, -2090572700, 1, "CutsceneEditor.SetDuration", "menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_Dur", 320, 5, 205, 20)
	XGUIEng.ShowWidget("CutsceneEditor_Dur", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_Dur", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateStaticTextWidgetChild("CutsceneEditor_PointEdit", "CutsceneEditor_SpeedText", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_SpeedText", 225, 30, 90, 20)
	XGUIEng.ShowWidget("CutsceneEditor_SpeedText", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_SpeedText", 0, false, false)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_SpeedText", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_SpeedText", 0, 100, 100, 100, 0)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_SpeedText", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_SpeedText", 0)
	XGUIEng.SetText("CutsceneEditor_SpeedText", "from speed:", 1)
	XGUIEng.SetTextColor("CutsceneEditor_SpeedText", 255, 255, 255, 255)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_SpeedText", true)
	XGUIEng.SetLinesToPrint("CutsceneEditor_SpeedText", 0, 0)
	CppLogic.UI.StaticTextWidgetSetLineDistanceFactor("CutsceneEditor_SpeedText", 0)
	CppLogic.UI.ContainerWidgetCreateCustomWidgetChild("CutsceneEditor_PointEdit", "CutsceneEditor_Speed", "CppLogic::Mod::UI::TextInputCustomWidget", nil, 5, 0, 0, 0, -2090572700, 10, "CutsceneEditor.SetDurationFromSpeed", "menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_Speed", 320, 30, 205, 20)
	XGUIEng.ShowWidget("CutsceneEditor_Speed", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_Speed", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateContainerWidgetChild("CutsceneEditor_Edit", "CutsceneEditor_NumericCam", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_NumericCam", 0, 0, 370, 80)
	XGUIEng.ShowWidget("CutsceneEditor_NumericCam", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_NumericCam", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateStaticTextWidgetChild("CutsceneEditor_NumericCam", "CutsceneEditor_NC_x", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_NC_x", 5, 5, 20, 20)
	XGUIEng.ShowWidget("CutsceneEditor_NC_x", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_NC_x", 0, false, false)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_NC_x", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_NC_x", 0, 100, 100, 100, 0)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_NC_x", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_NC_x", 0)
	XGUIEng.SetText("CutsceneEditor_NC_x", "x", 1)
	XGUIEng.SetTextColor("CutsceneEditor_NC_x", 255, 255, 255, 255)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_NC_x", false)
	CppLogic.UI.WidgetOverrideUpdateFunc("CutsceneEditor_NC_x", function() CutsceneEditor.UpdateNumericCam() end)
	XGUIEng.SetLinesToPrint("CutsceneEditor_NC_x", 0, 0)
	CppLogic.UI.StaticTextWidgetSetLineDistanceFactor("CutsceneEditor_NC_x", 0)
	CppLogic.UI.ContainerWidgetCreateStaticTextWidgetChild("CutsceneEditor_NumericCam", "CutsceneEditor_NC_y", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_NC_y", 5, 30, 20, 20)
	XGUIEng.ShowWidget("CutsceneEditor_NC_y", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_NC_y", 0, false, false)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_NC_y", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_NC_y", 0, 100, 100, 100, 0)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_NC_y", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_NC_y", 0)
	XGUIEng.SetText("CutsceneEditor_NC_y", "y", 1)
	XGUIEng.SetTextColor("CutsceneEditor_NC_y", 255, 255, 255, 255)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_NC_y", true)
	XGUIEng.SetLinesToPrint("CutsceneEditor_NC_y", 0, 0)
	CppLogic.UI.StaticTextWidgetSetLineDistanceFactor("CutsceneEditor_NC_y", 0)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("CutsceneEditor_NumericCam", "CutsceneEditor_NC_z", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_NC_z", 5, 55, 15, 20)
	XGUIEng.ShowWidget("CutsceneEditor_NC_z", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_NC_z", 0, false, false)
	XGUIEng.DisableButton("CutsceneEditor_NC_z", 0)
	XGUIEng.HighLightButton("CutsceneEditor_NC_z", 0)
	CppLogic.UI.ButtonOverrideActionFunc("CutsceneEditor_NC_z", function() CutsceneEditor.JumpHeightOverTerrain() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_NC_z", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_NC_z", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_NC_z", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_NC_z", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_NC_z", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_NC_z", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_NC_z", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_NC_z", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_NC_z", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_NC_z", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("CutsceneEditor_NC_z", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_NC_z", true)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_NC_z", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_NC_z", 0)
	XGUIEng.SetText("CutsceneEditor_NC_z", "z", 1)
	XGUIEng.SetTextColor("CutsceneEditor_NC_z", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("CutsceneEditor_NC_z", true)
	CppLogic.UI.ContainerWidgetCreateCustomWidgetChild("CutsceneEditor_NumericCam", "CutsceneEditor_NC_xin", "CppLogic::Mod::UI::TextInputCustomWidget", nil, 5, 2, 0, 0, -2090572700, 5, "CutsceneEditor.NumericCamXY", "menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_NC_xin", 25, 5, 150, 20)
	XGUIEng.ShowWidget("CutsceneEditor_NC_xin", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_NC_xin", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateCustomWidgetChild("CutsceneEditor_NumericCam", "CutsceneEditor_NC_yin", "CppLogic::Mod::UI::TextInputCustomWidget", nil, 5, 2, 0, 0, -2090572700, 5, "CutsceneEditor.NumericCamXY", "menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_NC_yin", 25, 30, 150, 20)
	XGUIEng.ShowWidget("CutsceneEditor_NC_yin", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_NC_yin", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateCustomWidgetChild("CutsceneEditor_NumericCam", "CutsceneEditor_NC_zin", "CppLogic::Mod::UI::TextInputCustomWidget", nil, 5, 0, 0, 0, -2090572700, 5, "CutsceneEditor.NumericCamSet", "menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_NC_zin", 25, 55, 150, 20)
	XGUIEng.ShowWidget("CutsceneEditor_NC_zin", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_NC_zin", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateStaticTextWidgetChild("CutsceneEditor_NumericCam", "CutsceneEditor_NC_pitch", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_NC_pitch", 180, 5, 40, 20)
	XGUIEng.ShowWidget("CutsceneEditor_NC_pitch", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_NC_pitch", 0, false, false)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_NC_pitch", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_NC_pitch", 0, 100, 100, 100, 0)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_NC_pitch", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_NC_pitch", 0)
	XGUIEng.SetText("CutsceneEditor_NC_pitch", "pitch", 1)
	XGUIEng.SetTextColor("CutsceneEditor_NC_pitch", 255, 255, 255, 255)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_NC_pitch", true)
	XGUIEng.SetLinesToPrint("CutsceneEditor_NC_pitch", 0, 0)
	CppLogic.UI.StaticTextWidgetSetLineDistanceFactor("CutsceneEditor_NC_pitch", 0)
	CppLogic.UI.ContainerWidgetCreateStaticTextWidgetChild("CutsceneEditor_NumericCam", "CutsceneEditor_NC_yaw", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_NC_yaw", 180, 30, 40, 20)
	XGUIEng.ShowWidget("CutsceneEditor_NC_yaw", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_NC_yaw", 0, false, false)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_NC_yaw", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_NC_yaw", 0, 100, 100, 100, 0)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_NC_yaw", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_NC_yaw", 0)
	XGUIEng.SetText("CutsceneEditor_NC_yaw", "yaw", 1)
	XGUIEng.SetTextColor("CutsceneEditor_NC_yaw", 255, 255, 255, 255)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_NC_yaw", true)
	XGUIEng.SetLinesToPrint("CutsceneEditor_NC_yaw", 0, 0)
	CppLogic.UI.StaticTextWidgetSetLineDistanceFactor("CutsceneEditor_NC_yaw", 0)
	CppLogic.UI.ContainerWidgetCreateCustomWidgetChild("CutsceneEditor_NumericCam", "CutsceneEditor_NC_pitchin", "CppLogic::Mod::UI::TextInputCustomWidget", nil, 3, 2, 0, 0, -2090572700, 5, "CutsceneEditor.NumericCamPitch", "menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_NC_pitchin", 220, 5, 150, 20)
	XGUIEng.ShowWidget("CutsceneEditor_NC_pitchin", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_NC_pitchin", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateCustomWidgetChild("CutsceneEditor_NumericCam", "CutsceneEditor_NC_yawin", "CppLogic::Mod::UI::TextInputCustomWidget", nil, 3, 2, 0, 0, -2090572700, 5, "CutsceneEditor.NumericCamYaw", "menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_NC_yawin", 220, 30, 150, 20)
	XGUIEng.ShowWidget("CutsceneEditor_NC_yawin", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_NC_yawin", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateStaticTextWidgetChild("CutsceneEditor_NumericCam", "CutsceneEditor_NC_speed", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_NC_speed", 180, 55, 40, 20)
	XGUIEng.ShowWidget("CutsceneEditor_NC_speed", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_NC_speed", 0, false, false)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_NC_speed", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_NC_speed", 0, 100, 100, 100, 0)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_NC_speed", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_NC_speed", 0)
	XGUIEng.SetText("CutsceneEditor_NC_speed", "speed", 1)
	XGUIEng.SetTextColor("CutsceneEditor_NC_speed", 255, 255, 255, 255)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_NC_speed", true)
	XGUIEng.SetLinesToPrint("CutsceneEditor_NC_speed", 0, 0)
	CppLogic.UI.StaticTextWidgetSetLineDistanceFactor("CutsceneEditor_NC_speed", 0)
	CppLogic.UI.ContainerWidgetCreateCustomWidgetChild("CutsceneEditor_NumericCam", "CutsceneEditor_NC_speedin", "CppLogic::Mod::UI::TextInputCustomWidget", nil, 4, 0, 0, 0, -2090572700, 5, "CutsceneEditor.NumericCamSpeed", "menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_NC_speedin", 220, 55, 150, 20)
	XGUIEng.ShowWidget("CutsceneEditor_NC_speedin", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_NC_speedin", 0, false, false)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("CutsceneEditor_Edit", "CutsceneEditor_ToSelect", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_ToSelect", 974, 628, 50, 20)
	XGUIEng.ShowWidget("CutsceneEditor_ToSelect", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_ToSelect", 0, false, false)
	XGUIEng.DisableButton("CutsceneEditor_ToSelect", 0)
	XGUIEng.HighLightButton("CutsceneEditor_ToSelect", 0)
	CppLogic.UI.ButtonOverrideActionFunc("CutsceneEditor_ToSelect", function() CutsceneEditor.ToSelect() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_ToSelect", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_ToSelect", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_ToSelect", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_ToSelect", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_ToSelect", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_ToSelect", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_ToSelect", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_ToSelect", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_ToSelect", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_ToSelect", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("CutsceneEditor_ToSelect", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_ToSelect", true)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_ToSelect", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_ToSelect", 0)
	XGUIEng.SetText("CutsceneEditor_ToSelect", "select", 1)
	XGUIEng.SetTextColor("CutsceneEditor_ToSelect", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("CutsceneEditor_ToSelect", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("CutsceneEditor_Edit", "CutsceneEditor_Export", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_Export", 974, 653, 50, 20)
	XGUIEng.ShowWidget("CutsceneEditor_Export", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_Export", 0, false, false)
	XGUIEng.DisableButton("CutsceneEditor_Export", 0)
	XGUIEng.HighLightButton("CutsceneEditor_Export", 0)
	CppLogic.UI.ButtonOverrideActionFunc("CutsceneEditor_Export", function() CutsceneEditor.Store() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_Export", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_Export", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_Export", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_Export", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_Export", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_Export", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_Export", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_Export", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_Export", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_Export", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("CutsceneEditor_Export", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_Export", true)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_Export", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_Export", 0)
	XGUIEng.SetText("CutsceneEditor_Export", "export", 1)
	XGUIEng.SetTextColor("CutsceneEditor_Export", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("CutsceneEditor_Export", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("CutsceneEditor_Edit", "CutsceneEditor_PreviewFlight", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_PreviewFlight", 974, 678, 50, 40)
	XGUIEng.ShowWidget("CutsceneEditor_PreviewFlight", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_PreviewFlight", 0, false, false)
	XGUIEng.DisableButton("CutsceneEditor_PreviewFlight", 0)
	XGUIEng.HighLightButton("CutsceneEditor_PreviewFlight", 0)
	CppLogic.UI.ButtonOverrideActionFunc("CutsceneEditor_PreviewFlight", function() CutsceneEditor.Preview(true) end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_PreviewFlight", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_PreviewFlight", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_PreviewFlight", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_PreviewFlight", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_PreviewFlight", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_PreviewFlight", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_PreviewFlight", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_PreviewFlight", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_PreviewFlight", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_PreviewFlight", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("CutsceneEditor_PreviewFlight", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_PreviewFlight", true)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_PreviewFlight", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_PreviewFlight", 0)
	XGUIEng.SetText("CutsceneEditor_PreviewFlight", "@center view @cr flight", 1)
	XGUIEng.SetTextColor("CutsceneEditor_PreviewFlight", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("CutsceneEditor_PreviewFlight", true)
	CppLogic.UI.ContainerWidgetCreateTextButtonWidgetChild("CutsceneEditor_Edit", "CutsceneEditor_Preview", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_Preview", 974, 723, 50, 20)
	XGUIEng.ShowWidget("CutsceneEditor_Preview", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_Preview", 0, false, false)
	XGUIEng.DisableButton("CutsceneEditor_Preview", 0)
	XGUIEng.HighLightButton("CutsceneEditor_Preview", 0)
	CppLogic.UI.ButtonOverrideActionFunc("CutsceneEditor_Preview", function() CutsceneEditor.Preview() end)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_Preview", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_Preview", 0, 100, 100, 100, 131)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_Preview", 1, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_Preview", 1, 150, 150, 150, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_Preview", 2, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_Preview", 2, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_Preview", 3, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_Preview", 3, 255, 255, 255, 255)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_Preview", 4, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_Preview", 4, 255, 255, 255, 255)
	CppLogic.UI.WidgetSetTooltipData("CutsceneEditor_Preview", nil, false, true)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_Preview", true)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_Preview", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_Preview", 0)
	XGUIEng.SetText("CutsceneEditor_Preview", "@center view", 1)
	XGUIEng.SetTextColor("CutsceneEditor_Preview", 255, 255, 255, 255)
	CppLogic.UI.TextButtonSetCenterText("CutsceneEditor_Preview", true)
	CppLogic.UI.ContainerWidgetCreateStaticTextWidgetChild("CutsceneEditor_Edit", "CutsceneEditor_ErrorMsg", nil)
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_ErrorMsg", 424, 5, 600, 70)
	XGUIEng.ShowWidget("CutsceneEditor_ErrorMsg", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_ErrorMsg", 0, false, false)
	CppLogic.UI.WidgetMaterialSetTextureCoordinates("CutsceneEditor_ErrorMsg", 0, 0, 0, 1, 1)
	XGUIEng.SetMaterialColor("CutsceneEditor_ErrorMsg", 0, 100, 100, 100, 0)
	CppLogic.UI.WidgetSetFont("CutsceneEditor_ErrorMsg", "data\\menu\\fonts\\onscreen10.met")
	CppLogic.UI.WidgetSetStringFrameDistance("CutsceneEditor_ErrorMsg", 0)
	XGUIEng.SetText("CutsceneEditor_ErrorMsg", "error msg", 1)
	XGUIEng.SetTextColor("CutsceneEditor_ErrorMsg", 255, 255, 255, 255)
	CppLogic.UI.WidgetSetUpdateManualFlag("CutsceneEditor_ErrorMsg", true)
	XGUIEng.SetLinesToPrint("CutsceneEditor_ErrorMsg", 0, 0)
	CppLogic.UI.StaticTextWidgetSetLineDistanceFactor("CutsceneEditor_ErrorMsg", 0)
	CppLogic.UI.ContainerWidgetCreateCustomWidgetChild("CutsceneEditor_Edit", "CutsceneEditor_EditCamControl", "CppLogic::Mod::UI::FreeCamCustomWidget", nil, 5, 0, 0, 0, 0, 0, "", "")
	CppLogic.UI.WidgetSetPositionAndSize("CutsceneEditor_EditCamControl", 0, 0, 1024, 768)
	XGUIEng.ShowWidget("CutsceneEditor_EditCamControl", 1)
	CppLogic.UI.WidgetSetBaseData("CutsceneEditor_EditCamControl", 0, false, false)
	
end
